app/blog/forms.py
from flask.ext.wtf import Form
from wtforms import TextAreaField, TextField, BooleanField, SubmitField
from wtforms.validators import Required, ValidationError


class PostForm(Form):
    title = TextField("title", validators=[Required()])
    body = TextAreaField("body", validators=[Required()])
    is_published = BooleanField("publish", default=False)
    submit = SubmitField("save")


def validate_confirm(form, field):
    if field.data != "yes":
        raise ValidationError("Please enter 'yes'")


class DeleteForm(Form):
    confirm = TextField("confirm", validators=[validate_confirm])
    submit = SubmitField("delete")

app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views

app/blog/views.py
from datetime import datetime

from flask import abort, flash, request, render_template, redirect, url_for
from flask.ext.login import login_required, current_user
from sqlalchemy import desc

from . import blog
from .forms import PostForm, DeleteForm

from ..models import db, Post


@blog.route('/')
@blog.route('/index')
@blog.route('/page/<int:page>')
def index(page=1):
    posts = (Post.query
                 .filter_by(is_published=True)
                 .order_by(desc(Post.timestamp))
                 .paginate(page, 3))
    return render_template('blog/index.html', posts=posts)


@blog.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    form = PostForm(request.form)
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.body.data,
                    timestamp=datetime.utcnow(),
                    user_id=int(current_user.get_id()),
                    is_published=form.is_published.data)
        db.session.add(post)
        db.session.commit()
        if form.is_published.data:
            flash("Post is now published.")
        else:
            flash("Post updated")

        return redirect('blog/'+post.slug)

    return render_template('blog/edit.html', form=form)


@blog.route('/<slug>/')
def show_post(slug):
    post = Post.query.filter_by(slug=slug).first()
    if post is not None:
        if post.is_published:
            return render_template('blog/post.html', post=post)
        else:
            if  current_user.is_authenticated:
                flash("This post is unpublished.")
                return render_template('blog/post.html', post=post)
            else:
                abort(401)
    else:
        abort(404)


@blog.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    post = Post.query.filter_by(slug=slug).first()
    if post is not None:
        if request.method == 'GET':
            form = PostForm(obj=post)
            return render_template('blog/edit.html', form=form)
        else:
            form = PostForm(request.form)
            post.title = form.title.data
            post.body = form.body.data
            post.is_published = form.is_published.data
            post.user_id = current_user.get_id()
            db.session.commit()
            flash("Post updated.")
            return redirect(url_for('blog.show_post', slug=post.slug))
    else:
        abort(404)


@blog.route('/<slug>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(slug):
    form = DeleteForm(request.form)
    post = Post.query.filter_by(slug=slug).first()
    if post is not None:
        if form.validate_on_submit():
            db.session.delete(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        else:
            return render_template("blog/delete.html", form=form)
    else:
        abort(404)


"""
@blog.route('/search/<search_terms>/')
def search():
    return render_template('blog/search.html')
"""


@blog.route('/archive')
@blog.route('/archive/page/<int:page>')
def archive(page=1):
    posts = (Post.query
                 .filter_by(is_published=True)
                 .order_by(desc(Post.timestamp))
                 .paginate(page, 10))
    return render_template('blog/archive.html',
                           head_title="Blog Archive",
                           header_title="Archives",
                           posts=posts)


@blog.route('/unpublished')
@login_required
def show_unpublished():
    posts = (Post.query
                 .filter_by(is_published=False)
                 .order_by(desc(Post.timestamp))
                 .paginate(1, 10))
    return render_template('blog/archive.html',
                           head_title="Administration",
                           header_title="Unpublished posts",
                           posts=posts)

app/templates/blog/archive.html
{% extends "blog/base.html" %}

{% block title %}{{ head_title }}{% endblock %}

{% block pretitle %}{{ header_title }} - {% endblock %}

{% block header_par %}{% endblock %}

{% block body_content %}
<section>
{% for post in posts.items %}
    <a href="{{ url_for ('blog.show_post', slug=post.slug) }}">
        <h3>{{ post.title }}</h3><p>by {{ post.author.nickname|title }}, {{ post.timestamp|timesince }}</p>
    </a>
{% endfor %}
</section>
<section>
    {% if posts.has_next %}
    <a href="{{ url_for('blog.archive', page=posts.next_num) }}">
        <span class="icon fa-chevron-circle-left fa-2x">
    </a>
    {% endif %}
    {% if posts.has_prev %}
    <a href="{{ url_for('blog.archive', page=posts.prev_num) }}">
        <span class="icon fa-chevron-circle-right fa-2x">
    </a>
    {% endif %}
</section>
{% endblock %}

app/templates/blog/base.html
{% extends "base.html" %}

{% block title %}Blog{% endblock %}

{% block body_header %}
<!-- Blog header -->
    <header>
        <div class="inner">
            <h2 class="major">{% block pretitle %}{% endblock %}Blog</h2>
            {% block header_par %}
            <a href="{{ url_for('blog.archive') }}">Archive</a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('blog.show_unpublished') }}">Unpublished</a>
            <a href="{{ url_for('blog.new') }}">New</a>
            {% endif %}
            {% endblock %}
        </div>
    </header>
{% endblock %}

app/templates/blog/delete.html
{% extends "/blog/base.html" %}

{% from "helpers.html" import render_text, render_textbox, render_checkbox, render_submit %}

{% block title %}Administration{% endblock %}

{% block pretitle %}Delete post - {% endblock %}

{% block header_par %}{% endblock %}

{% block body_content %}
<section>
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_text(form.confirm) }}
        {{ render_submit("Delete") }}
    </form>
</section>
{% endblock %}

app/templates/blog/edit.html
{% extends "blog/base.html" %}

{% from "helpers.html" import render_text, render_textbox, render_checkbox, render_submit %}

{% block pretitle %}Post editor - {% endblock %}

{% block header_par %}
{% endblock %}

{% block body_content %}
<section>
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_text(form.title) }}
        {{ render_textbox(form.body, 10) }}
        {{ render_checkbox(form.is_published) }}
        {{ render_submit("Save") }}
    </form>
</section>
{% endblock %}

app/templates/blog/index.html
{% extends "blog/base.html" %}

{% block body_content %}
{% for post in posts.items %}
<section>
    <a href="{{ url_for('blog.show_post', slug=post.slug) }}"><h3 class="major">{{ post.title }}</h3></a>
    <em>By {{ post.author.nickname|title }} / {{ post.timestamp|timesince }}</em>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('blog.edit_post', slug=post.slug) }}">Edit</a>
    {% endif %}
    <p>{{ post.body|markdown }}</p>
</section>
{% endfor %}
<section>
    {% if posts.has_next %}
    <a href="{{ url_for('blog.index', page=posts.next_num) }}">
        <span class="icon fa-chevron-circle-left fa-2x">
    </a>
    {% endif %}
    {% if posts.has_prev %}
    <a href="{{ url_for('blog.index', page=posts.prev_num) }}">
        <span class="icon fa-chevron-circle-right fa-2x">
    </a>
    {% endif %}
</section>
{% endblock %}

app/templates/blog/post.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block pretitle %}{{ post.title }} - {% endblock %}

{% block header_par %}
<p>author: {{ post.author.nickname|title }}, {{ post.timestamp|timesince }}</p>
{% if current_user.is_authenticated %}
<a href="{{ url_for('blog.edit_post', slug=post.slug) }}">Edit</a>
<a href="{{ url_for('blog.delete_post', slug=post.slug) }}">Delete</a>
{% endif %}
{% endblock %}

{% block body_content %}
    <section class="wrapper style2">
	<p>{{ post.body|markdown }}</p>
    </section>
{% endblock %}

app/templates/blog/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}